### ISSUE TITLE
Allow 'grey' color

### ISSUE THREAD

**Issue by xerus2000** [dbrgn/tealdeer#147]
And ideally even more, even ANSI escape codes provide a much bigger palette?

**Comment by tomasfarias** [comment]
I'm looking to get involved and would be happy to contribute a PR that adds a new `enum` variant to `RawColor` for ANSI escapes codes. Since the project already uses `ansi_term`, this variant can be matched to `ansi_term::Color::Fixed`.

This does mean a key, value pair would be needed in the config, though, which doesn't look as clean as simply writing the color name, but it does allow support for all ANSI escape codes, e.g.:
```
[style.command_name]
background = { ansi = 7 }
```

In a similar fashion, we can add another enum variant to support RGB codes:
```
[style.command_name]
foreground =  { rgb = { r = 255, g = 51, b = 255 } }
```
![image](https://user-images.githubusercontent.com/18740659/97789314-bee03400-1bbf-11eb-9081-317c47bb1930.png)

**Comment by dbrgn** [comment]
That looks good! I assume "plain" colors would work as before, without any breaking change?

**Comment by tomasfarias** [comment]
@dbrgn Yes! Regular plain colors as strings would still be supported without any changes, just tested this config:
```
[style.command_name]
foreground = "green"  # Light pink
background = { ansi = 123 }
```
![image](https://user-images.githubusercontent.com/18740659/97789706-d2d96500-1bc2-11eb-80cf-8731f5720885.png)
