### ISSUE TITLE
Fail to Update Cache

### ISSUE THREAD

**Issue by eleblanc** [dbrgn/tealdeer#160]
When I try to update tldr's cache, I keep getting the following error:

Could not update cache: HTTP error: error sending request for url (https://github.com/tldr-pages/tldr/archive/master.tar.gz): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution

Is there a way to define an alternative URL?

**Comment by dbrgn** [comment]
It seems that your DNS-server cannot resolve github.com. Since you're submitting this issue on github.com, this was probably a temporary issue?

Right now the URL is hardcoded, so there's no way to specify a custom URL. If this is a problem (e.g. because you cannot reach github.com due to a firewall), you could manually extract the tldr-pages archive to the cache directory (on Linux it's usually `~/.cache/tealdeer/tldr-master/`).

**Comment by weiss-d** [comment]
Hi, @dbrgn ! I can confirm the same issue, and my DNS settings are ok.
Installed `tealdeer-bin` from AUR.

```
➜  ~ tldr --update
Could not update cache: HTTP error: error sending request for url (https://github.com/tldr-pages/tldr/archive/master.tar.gz): error trying to connect: dns error: failed to lookup address information: Try again
➜  ~ ping github.com
PING github.com (140.82.121.4) 56(84) bytes of data.
64 bytes from 140.82.121.4: icmp_seq=1 ttl=50 time=98.2 ms
64 bytes from 140.82.121.4: icmp_seq=2 ttl=50 time=74.6 ms
```

**Comment by dbrgn** [comment]
@weiss-d I assume you're on Linux? Can you post the output of `dig github.com` or `nslookup github.com`?

**Comment by weiss-d** [comment]
It's kinda strange but both commands report timeout, when any single program that needs Internet, like the browser, where I'm typing this, works just fine.
```
➜  ~ dig github.com

; <<>> DiG 9.16.11 <<>> github.com
;; global options: +cmd
;; connection timed out; no servers could be reached

➜  ~ nslookup github.com
;; connection timed out; no servers could be reached
```

**Comment by dbrgn** [comment]
Browsers may have their own DNS cache (they might also use DNS-over-HTTP), but that wget works is weird...

You can try whether DNS lookups work if you specify a DNS server directly, e.g. `dig github.com 8.8.8.8` (this will use 8.8.8.8 as DNS and not your system-configured DNS).

In any case, the source of the problem is either a mis-configured DNS server in your system, or a DNS server that's currently down.

(For further research, take a look at `/etc/resolv.conf`.)
