### ISSUE TITLE
`cargo install tealdeer` should be present in the README

### ISSUE THREAD

**Issue by Valloric** [dbrgn/tealdeer#172]
The string `cargo install tealdeer` should show up in the README; the earlier in the file, the better.

**Comment by dbrgn** [comment]
Hi @Valloric, honored to see you here, thanks for your work on YCM!

Anyways, there are multiple ways to install tealdeer, and not every user has rustc / cargo installed.

The first non-intro paragraph in the README says:

![2021-04-02-002039_877x34_scrot](https://user-images.githubusercontent.com/105168/113360045-4f769800-9349-11eb-9c94-6b95dd19b8a6.png)

For the impatient people that don't read docs, this will get you started right away, just download and run (without any cargo / compilation step).

For people that want a proper installation, there are the [user docs](https://dbrgn.github.io/tealdeer/installing.html):

![2021-04-02-002050_886x128_scrot](https://user-images.githubusercontent.com/105168/113360068-59000000-9349-11eb-9179-e046149d982a.png)

I think this is the best approach, because it shows different options depending on your favorite way to install binaries (packet manager, cargo, static binaries, etc). `cargo install` is not necessarily the most user friendly way, because it requires cargo and also requires that you set up your $PATH properly to include `$HOME/.cargo/bin`.
