### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by qubidt** [dbrgn/tealdeer#207]
Any chance we could get a new release? zsh autocompletion is currently broken on the latest release (1.4.1) due to the `[` page. This was fixed a while ago by #168

**Comment by dbrgn** [comment]
Yes, I aim towards a release in the coming 1-2 months.

Note however that the zsh autocompletion can be fixed independently from a new tealdeer release, the fix is not part of tealdeer itself. What OS/Distro do you use? You could ask the packagers to update the zsh completion files. Or you could update it yourself in your system: https://github.com/dbrgn/tealdeer/blob/master/zsh_tealdeer

**Comment by qubidt** [comment]
Yup, I've done that myself. I just wanted to avoid having to remember to deploy this fix to all of my systems, especially since it's already being tracked by the package manager.

I'm using official package from the [Arch community repo](https://github.com/archlinux/svntogit-community/blob/09cdf616a3f7a73f8ef62c87a8c0b97dfc9a24da/trunk/PKGBUILD).

I have a feeling they'll tell me to ask for upstream to fix it, but I'll try to get in touch with the package maintainer, thanks

**Comment by dbrgn** [comment]
> I have a feeling they'll tell me to ask for upstream to fix it, but I'll try to get in touch with the package maintainer, thanks

I used to maintain the AUR package, but with it having moved to community, I can't fix it myself 🙂

You should be able to file a bugreport at https://bugs.archlinux.org/newtask?project=5&product_category=33&item_summary=%5Btealdeer%5D+PLEASE+ENTER+SUMMARY

**Comment by dbrgn** [comment]
1.5.0 is released: https://github.com/dbrgn/tealdeer/releases/tag/v1.5.0
