### ISSUE TITLE
Add option to invert order of commands and descriptions

### ISSUE THREAD

**Issue by yuuyins** [dbrgn/tealdeer#255]
I would like tealdeer to have an option to invert the order of the descriptions and commands. Because in situations when the terminal screen is little and the command has many entries and unless we scroll up, we can only see the last commands. This is a bad experience because generally the most basic and important commands are the first entries. 

### Example

The original ac

```md
# ac

> Print statistics on how long users have been connected.
> More information: <https://www.gnu.org/software/acct/manual/accounting.html#ac>.

- Print how long the current user has been connected in hours:

`ac`

- Print how long users have been connected in hours:

`ac --individual-totals`

- Print how long a particular user has been connected in hours:

`ac --individual-totals {{username}}`

- Print how long a particular user has been connected in hours per day (with total):

`ac --daily-totals --individual-totals {{username}}`

- Also display additional details:

`ac --compatibility`
```

would turn into
```md
# ac

> Print statistics on how long users have been connected.
> More information: <https://www.gnu.org/software/acct/manual/accounting.html#ac>.

- Also display additional details:

`ac --compatibility`

- Print how long a particular user has been connected in hours per day (with total):

`ac --daily-totals --individual-totals {{username}}`

- Print how long a particular user has been connected in hours:

`ac --individual-totals {{username}}`

- Print how long users have been connected in hours:

`ac --individual-totals`

- Print how long the current user has been connected in hours:

`ac`
```

OR (i don't like this one because I generally don't need those information about name, description, website).
```md
- Also display additional details:

`ac --compatibility`

- Print how long a particular user has been connected in hours per day (with total):

`ac --daily-totals --individual-totals {{username}}`

- Print how long a particular user has been connected in hours:

`ac --individual-totals {{username}}`

- Print how long users have been connected in hours:

`ac --individual-totals`

- Print how long the current user has been connected in hours:

`ac`

> Print statistics on how long users have been connected.
> More information: <https://www.gnu.org/software/acct/manual/accounting.html#ac>.

# ac
```

**Comment by niklasmohrin** [comment]
This is definitely possible to implement, we would need another indirection though. I feel like the format proposed here it more difficult to read, because I have to move up and down when reading headings and examples.

If having to scroll up to see the results is a problem, have you tried using `--pager`? This way, you could have the information in the correct order but also be able to read the top lines right away.

**Comment by dbrgn** [comment]
For me, this is an edge case and I wouldn't want to implement this feature request. It considerably increases the complexity of the output code, and instead of streaming the lines out, you would need to fully load them into memory, parse them, and then output them in the desired order.

A pager might be the better approach.

You could also consider creating a script that goes through the cached pages and rewrites them in your desired orderY. (Unless you activate automatic cache updates in the settings, tealdeer will not silently overwrite the cache.)

I'd vote for closing this feature request, do you agree @niklasmohrin?

**Comment by niklasmohrin** [comment]
Yes, but let's be fair and allow another attempt at convincing us :)

**Comment by yuuyins** [comment]
I hadn't seen that pager option. I've set it to true in the config and It suffices my needs. Thanks!
