### ISSUE TITLE
"Semi-compact" mode?

### ISSUE THREAD

**Issue by giorgiovilardo** [dbrgn/tealdeer#264]
Hello,

first of all thanks for your efforts on the client - it's very fast and pleasant to use; I'm firm in the camp that cli tools must be quick in replying to its user, and `tealdeer` is very quick making it excellent to use.

One pet peeve of mine is that I'm not able to recreate the C or python client look and feel, with a response structure of the example commands like this:

```
Example text
    example command
<linebreak>
```

Compact mode is too compact for me right now (no break between examples) and standard mode takes too much vertical space with all those breaks. Both are not super easy to scan for my eyes.

I might get used to compact mode and maybe even appreciate it long term, but for now I'm more of the idea of forking and implementing some sort of semi-compact mode, mimicking the python client output. I thought it would be cool to ask if the devteam is eventually insterested in a PR implementing this other display mode, if only to try and do some better work, as if I implement this for just me I'll probably take a hacky/quick route to success.

If you are actually interested, maybe we can have a small chat on how to design it and implement it, as right now the display mode is a bool and this would introduce a third way so it kinda needs some re-engineering. Keep in mind I'm not a rust programmer, so if you think this feature could be complex, please advise against it; I'd rather not commit to very hard or long tasks as I don't have tons of free time as of now. I say this because I took a quick look at the code and it seems like a impactful PR all in all.

Thanks!

**Comment by niklasmohrin** [comment]
Interesting :thinking: Implementing this will need some work, because we currently don't distinguish between the different "kinds of empty lines". You would somehow need to communicate this between `line_iterator.rs` and `formatter.rs`.

As for my take on this: I think it would be interesting to allow for more customization like the one suggested, but it's hard to decide where to draw the line. We could probably implement your desired mode into the existing code, but it gets harder and harder with every addition. The next step would be trimming the spaces at the beginning of the command, should we allow this? Why can I make such precise decisions about linebreaks, but not list the entries in reverse order (#255)?

I feel like we could at some point make some decisions and implement more modes (that could totally be suggested in this discussion here), but I can't make promises. @dbrgn What is your opinion on this?

**Comment by giorgiovilardo** [comment]
@niklasmohrin I agree with your analysis wholeheartedly; I also think that it's maybe too much of an hassle to start having many different types of linebreaks, even if semantically that could be the place where the line is drawn, as a linebreak after the title has not the same semantic meaning of the closing \n of the file. But detection can also be very messy as it starts to rely on unreliable things like items before/after in the lines array and whatnot.

I also dove a bit deeper in the code and probably the way to have more customization is to start encapsulating things in `Page` structs which seems to not be interesting for the objective of the projects as it should impact performance.

**Comment by dbrgn** [comment]
Yeah, I agree. It would definitely add more complexity to the parsing and output code. If a lot of people would think that this is useful, then we could think about it (please give a :+1: to the issue), so let's keep the issue open for now. However, right now I don't think it's worth the complexity-usefulness tradeoff.

**Comment by dbrgn** [comment]
For now I'll close this issue to keep the issue tracker cleaner. If someone feels this would be useful, feel free to still give the initial post a 👍🏻 reaction.

**Comment by eugenesvk** [comment]
But it's harder to post a 👍🏻 reaction on a closed issue because it's harder to find it!
