### ISSUE TITLE
Code blocks not supported?

### ISSUE THREAD

**Issue by jgogstad** [dbrgn/tealdeer#265]
Are code blocks not supported?

~~~
❯ cat foo.md
# Foo

- Something

``` python
print foo
```
❯ tldr --render foo.md

  Something




❯
~~~

If I read the spec correctly, this should be supported

- https://github.com/tldr-pages/tldr/blob/main/CLIENT-SPECIFICATION.md#page-structure
- https://spec.commonmark.org/0.30/#example-24

(The space between the triple ticks and "python" is not significant, just followed the example from the CommonMark spec)

**Comment by dbrgn** [comment]
Hm, that section in the spec wasn't there when I started this project. Tealdeer is not a commonmark renderer, it uses a custom fast parser that handles the format specified by the TLDR pages.

The spec notes:

> Clients MUST NOT break if the page format is changed within the CommonMark specification.

We fulfil that requirement, it doesn't break but there's simply no special rendering being done.

Right now I'd be against full commonmark compatibility, since the vast majority of pages will probably use the standard markup, and it would add considerably more complexity to this project.

**Comment by dbrgn** [comment]
(Note: You might be interested in [bat](https://github.com/sharkdp/bat) as a console based markdown renderer.)

**Comment by jgogstad** [comment]
Ok, thanks for the reply.
