### ISSUE TITLE
Support config file like .tldrrc

### ISSUE THREAD

**Issue by KarlFiabeschi** [dbrgn/tealdeer#33]

**Comment by dbrgn** [comment]
@KarlFiabeschi what would you configure in that file?

**Comment by KarlFiabeschi** [comment]
Maybe i'm wrong but stuff like:

default os override;
default color schema;
default cache dir;

:)

**Comment by jtojnar** [comment]
If this is implemented, it should also respect [XDG basedir specification](https://standards.freedesktop.org/basedir-spec/latest/) – if `$XDG_CONFIG_HOME` is set, `$XDG_CONFIG_HOME/tealdeer/config` file should be loaded, otherwise it should fall back to `~/.config/tealdeer/config`.

See [Arch wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support) for more information.

**Comment by dbrgn** [comment]
Of course, our cache also conforms to the XDG basedir spec :)

**Comment by dbrgn** [comment]
> default os override;

Hm, the OS is autodetected by default. Can you name a use case where a permanent override would be desired?

> default color schema;

I can see that, but first we'd need to support color themes :)

> default cache dir;

We conform to the XDG specification and the tldr guys are discussing about actually standardizing the location. I don't think this should be configurable, unless someone can give me a good reason :)

I'm open to a pull request adding support for color themes and config files, I don't currently have much time to implement it myself though.
