### ISSUE TITLE
Cache not found but update successful

### ISSUE THREAD

**Issue by mat-m** [dbrgn/tealdeer#371]
on RedHat 8, with tldr 1.4.1

The cache is updated and filled (41M), but the command do not find it.

Technical info below

```bash
~/[0]>tldr ls
Cache not found. Please run `tldr --update`.
~/[1]>tldr --update
Successfully updated cache.
~/[0]>echo $?
0
~/[0]>ls -ln /home/env/adlbin/.cache/tealdeer/tldr-main/ | tail -2
-rw-rw-r--  1 994 932    45 Jul 11 19:49 requirements.txt
drwxrwxr-x  3 994 932  4096 Jul 12 17:30 scripts
~/[0]>tldr ls
Cache not found. Please run `tldr --update`.
~/[1]>tldr -v
tealdeer v1.4.1 (Linux)
~/[0]>file $(which tldr)
/usr/local/bin/tldr: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped

```

**Comment by niklasmohrin** [comment]
The problem is that when v1.4.1 was released (September 2020!), the pages repository still used "master" as the main branch name and we thus expect the folder to be called `tldr-master` (see [here in the code](https://github.com/dbrgn/tealdeer/blob/30b7c5febc2f51bd4db824f80586ba4b140fff26/src/main.rs#L91)). However, when downloading from https://github.com/tldr-pages/tldr/archive/master.tar.gz , we get a file named tldr-main.zip (and also containing the folder tldr-main, as seen in your output).

As a workaround, you can rename the folder under `.cache/tealeer` so that it is called `tldr-master` instead. The best solution however would be to update to a newer version - nowadays, the pages come through an archive from tldr.sh that should be more stable than the direct github download.

**Comment by mat-m** [comment]
Since I can't control the version installed, I symlinked tldr-master to tldr-main.

Thank you for the explanation, that helped

**Comment by ernstki** [comment]
> The problem is that when v1.4.1 was released (September 2020!)

I'm happy to have a workaround, but please allow me to respectfully make a case for trying to keep old things working, too.

If it were an oh-dot-something software, okay, it would be a different story, but it's a one-dot-something software. My gut tells me that simply keeping the `master` branch where it was and moving forward with `main` would let all your 1.4.1 installs working forever.

Maybe you were concerned that keeping an out-of-date `master` branch (stuck in the 1.4.1 days) around might confuse people. That seems legit. If that was the case, I understand.

Thanks, regardless.

**Comment by niklasmohrin** [comment]
I agree, however, the missing branch is from the tldr-pages repository and not ours. Today's tealdeer does some automatic migration for backwards compatibility, but our build from 2020 could not predict that the structure of the pages archive would change, so there is no backwards migration.

I suppose we could release some 1.4.1 build with such a backwards migration, but I am unsure I want to publish a release with outdated dependencies. If the demand is high enough (and we would know that our patch-release would make it into distro repositories where the problem currently occurs), I suppose we could check whether we can come up with something

**Comment by ernstki** [comment]
> I agree, however, the missing branch is from the tldr-pages repository and not ours.

That's a good point, which I hadn't considered. I don't suppose there's a demand for it, and regarding the distros, I believe that would be the distro package maintainers' responsibility anyway, not yours. As for end users, even in our definitely-not-cutting-edge HPC environment I was easily able to build a new binary.

Thanks for your thoughtful reply.
