### ISSUE TITLE
Support multiple languages

### ISSUE THREAD

**Issue by codesections** [dbrgn/tealdeer#96]
`tealdeer` currently fetches all languages from the tldr.sh API.  However, it only ever displays English documentation.  It seems that `tealdeer` should offer a flag/config option that would display documentation from other languages, when available.  (Or maybe it should read the `$LANG` environmental variable?)

Alternatively, if `tealdeer` is not going to display non-English documentation, it probably should not save the non-English docs in the user's cache (since they take up space without providing any benefit).

In an ideal world, `tealdeer` would offer a user the option of selecting their language(s) before downloading the cache, but that seems like a lower priority.

**Comment by dbrgn** [comment]
Yep, multilingual tldr pages are newer than tealdeer.

Would be nice to support all languages.

**Comment by dbrgn** [comment]
Actually, since tealdeer already supports the entire tldr pages repo, all languages will already be part of the cache (in `$XDG_CACHE_HOME/tealdeer/tldr-master/`).

What would be required:

- Add a config option to set the desired language
- If a page in that language exists, show it, otherwise fall back to the non-translated pages
- Add a command line argument (`-t/--translation`? Unfortunately `-l` is already used by `-l/--list`) to override the language

**Comment by dbrgn** [comment]
Ah, there is a language resolution spec here: https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md#language We should probably adhere to it.
